// Code generated by protoc-gen-go. DO NOT EDIT.
// source: transaction.proto

package model

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CollectedCoinRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               int64    `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Value                float64  `protobuf:"fixed64,3,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CollectedCoinRequest) Reset()         { *m = CollectedCoinRequest{} }
func (m *CollectedCoinRequest) String() string { return proto.CompactTextString(m) }
func (*CollectedCoinRequest) ProtoMessage()    {}
func (*CollectedCoinRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{0}
}

func (m *CollectedCoinRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CollectedCoinRequest.Unmarshal(m, b)
}
func (m *CollectedCoinRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CollectedCoinRequest.Marshal(b, m, deterministic)
}
func (m *CollectedCoinRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CollectedCoinRequest.Merge(m, src)
}
func (m *CollectedCoinRequest) XXX_Size() int {
	return xxx_messageInfo_CollectedCoinRequest.Size(m)
}
func (m *CollectedCoinRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CollectedCoinRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CollectedCoinRequest proto.InternalMessageInfo

func (m *CollectedCoinRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CollectedCoinRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *CollectedCoinRequest) GetValue() float64 {
	if m != nil {
		return m.Value
	}
	return 0
}

type CollectedCoinResponse struct {
	ValueAll             int64    `protobuf:"varint,1,opt,name=value_all,json=valueAll,proto3" json:"value_all,omitempty"`
	TrophyCoinId         int64    `protobuf:"varint,2,opt,name=trophy_coin_id,json=trophyCoinId,proto3" json:"trophy_coin_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CollectedCoinResponse) Reset()         { *m = CollectedCoinResponse{} }
func (m *CollectedCoinResponse) String() string { return proto.CompactTextString(m) }
func (*CollectedCoinResponse) ProtoMessage()    {}
func (*CollectedCoinResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{1}
}

func (m *CollectedCoinResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CollectedCoinResponse.Unmarshal(m, b)
}
func (m *CollectedCoinResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CollectedCoinResponse.Marshal(b, m, deterministic)
}
func (m *CollectedCoinResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CollectedCoinResponse.Merge(m, src)
}
func (m *CollectedCoinResponse) XXX_Size() int {
	return xxx_messageInfo_CollectedCoinResponse.Size(m)
}
func (m *CollectedCoinResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CollectedCoinResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CollectedCoinResponse proto.InternalMessageInfo

func (m *CollectedCoinResponse) GetValueAll() int64 {
	if m != nil {
		return m.ValueAll
	}
	return 0
}

func (m *CollectedCoinResponse) GetTrophyCoinId() int64 {
	if m != nil {
		return m.TrophyCoinId
	}
	return 0
}

type KilledMonsterRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               int64    `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MonsterId            int64    `protobuf:"varint,3,opt,name=monster_id,json=monsterId,proto3" json:"monster_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KilledMonsterRequest) Reset()         { *m = KilledMonsterRequest{} }
func (m *KilledMonsterRequest) String() string { return proto.CompactTextString(m) }
func (*KilledMonsterRequest) ProtoMessage()    {}
func (*KilledMonsterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{2}
}

func (m *KilledMonsterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KilledMonsterRequest.Unmarshal(m, b)
}
func (m *KilledMonsterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KilledMonsterRequest.Marshal(b, m, deterministic)
}
func (m *KilledMonsterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KilledMonsterRequest.Merge(m, src)
}
func (m *KilledMonsterRequest) XXX_Size() int {
	return xxx_messageInfo_KilledMonsterRequest.Size(m)
}
func (m *KilledMonsterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_KilledMonsterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_KilledMonsterRequest proto.InternalMessageInfo

func (m *KilledMonsterRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *KilledMonsterRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *KilledMonsterRequest) GetMonsterId() int64 {
	if m != nil {
		return m.MonsterId
	}
	return 0
}

type KilledMonsterResponse struct {
	QtdAll               int64    `protobuf:"varint,1,opt,name=qtd_all,json=qtdAll,proto3" json:"qtd_all,omitempty"`
	TrophyMonsterId      int64    `protobuf:"varint,2,opt,name=trophy_monster_id,json=trophyMonsterId,proto3" json:"trophy_monster_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KilledMonsterResponse) Reset()         { *m = KilledMonsterResponse{} }
func (m *KilledMonsterResponse) String() string { return proto.CompactTextString(m) }
func (*KilledMonsterResponse) ProtoMessage()    {}
func (*KilledMonsterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{3}
}

func (m *KilledMonsterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KilledMonsterResponse.Unmarshal(m, b)
}
func (m *KilledMonsterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KilledMonsterResponse.Marshal(b, m, deterministic)
}
func (m *KilledMonsterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KilledMonsterResponse.Merge(m, src)
}
func (m *KilledMonsterResponse) XXX_Size() int {
	return xxx_messageInfo_KilledMonsterResponse.Size(m)
}
func (m *KilledMonsterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_KilledMonsterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_KilledMonsterResponse proto.InternalMessageInfo

func (m *KilledMonsterResponse) GetQtdAll() int64 {
	if m != nil {
		return m.QtdAll
	}
	return 0
}

func (m *KilledMonsterResponse) GetTrophyMonsterId() int64 {
	if m != nil {
		return m.TrophyMonsterId
	}
	return 0
}

type DeathRequest struct {
	Id                   int64                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               int64                `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Time                 *timestamp.Timestamp `protobuf:"bytes,3,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *DeathRequest) Reset()         { *m = DeathRequest{} }
func (m *DeathRequest) String() string { return proto.CompactTextString(m) }
func (*DeathRequest) ProtoMessage()    {}
func (*DeathRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{4}
}

func (m *DeathRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeathRequest.Unmarshal(m, b)
}
func (m *DeathRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeathRequest.Marshal(b, m, deterministic)
}
func (m *DeathRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeathRequest.Merge(m, src)
}
func (m *DeathRequest) XXX_Size() int {
	return xxx_messageInfo_DeathRequest.Size(m)
}
func (m *DeathRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeathRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeathRequest proto.InternalMessageInfo

func (m *DeathRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DeathRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *DeathRequest) GetTime() *timestamp.Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

type DeathResponse struct {
	QtdAll               int64    `protobuf:"varint,1,opt,name=qtd_all,json=qtdAll,proto3" json:"qtd_all,omitempty"`
	TrophyDeathId        int64    `protobuf:"varint,2,opt,name=trophy_death_id,json=trophyDeathId,proto3" json:"trophy_death_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeathResponse) Reset()         { *m = DeathResponse{} }
func (m *DeathResponse) String() string { return proto.CompactTextString(m) }
func (*DeathResponse) ProtoMessage()    {}
func (*DeathResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{5}
}

func (m *DeathResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeathResponse.Unmarshal(m, b)
}
func (m *DeathResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeathResponse.Marshal(b, m, deterministic)
}
func (m *DeathResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeathResponse.Merge(m, src)
}
func (m *DeathResponse) XXX_Size() int {
	return xxx_messageInfo_DeathResponse.Size(m)
}
func (m *DeathResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeathResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeathResponse proto.InternalMessageInfo

func (m *DeathResponse) GetQtdAll() int64 {
	if m != nil {
		return m.QtdAll
	}
	return 0
}

func (m *DeathResponse) GetTrophyDeathId() int64 {
	if m != nil {
		return m.TrophyDeathId
	}
	return 0
}

func init() {
	proto.RegisterType((*CollectedCoinRequest)(nil), "model.CollectedCoinRequest")
	proto.RegisterType((*CollectedCoinResponse)(nil), "model.CollectedCoinResponse")
	proto.RegisterType((*KilledMonsterRequest)(nil), "model.KilledMonsterRequest")
	proto.RegisterType((*KilledMonsterResponse)(nil), "model.KilledMonsterResponse")
	proto.RegisterType((*DeathRequest)(nil), "model.DeathRequest")
	proto.RegisterType((*DeathResponse)(nil), "model.DeathResponse")
}

func init() { proto.RegisterFile("transaction.proto", fileDescriptor_2cc4e03d2c28c490) }

var fileDescriptor_2cc4e03d2c28c490 = []byte{
	// 392 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xdb, 0x6a, 0xe3, 0x30,
	0x10, 0x86, 0x71, 0xb2, 0x39, 0x4d, 0x0e, 0xbb, 0xab, 0x75, 0x48, 0x70, 0xb6, 0x34, 0x98, 0x52,
	0x42, 0x2f, 0x1c, 0x48, 0xe9, 0x03, 0x94, 0xf4, 0xc6, 0x94, 0x40, 0x31, 0xe9, 0x4d, 0x29, 0x35,
	0x4e, 0xa4, 0x26, 0x02, 0xd9, 0x72, 0x2c, 0xb9, 0xd0, 0xd7, 0xed, 0x93, 0x14, 0x4b, 0xce, 0x11,
	0x43, 0xc9, 0xa5, 0xfe, 0x19, 0xfd, 0xf3, 0x31, 0xff, 0xc0, 0x5f, 0x99, 0x04, 0x91, 0x08, 0x96,
	0x92, 0xf2, 0xc8, 0x89, 0x13, 0x2e, 0x39, 0xaa, 0x84, 0x1c, 0x13, 0x66, 0x5d, 0xae, 0x38, 0x5f,
	0x31, 0x32, 0x56, 0xe2, 0x22, 0x7d, 0x1f, 0x4b, 0x1a, 0x12, 0x21, 0x83, 0x30, 0xd6, 0x7d, 0xf6,
	0x33, 0x98, 0x53, 0xce, 0x18, 0x59, 0x4a, 0x82, 0xa7, 0x9c, 0x46, 0x1e, 0xd9, 0xa4, 0x44, 0x48,
	0xd4, 0x81, 0x12, 0xc5, 0x7d, 0x63, 0x68, 0x8c, 0xca, 0x5e, 0x89, 0x62, 0xd4, 0x83, 0x5a, 0x2a,
	0x48, 0xe2, 0x53, 0xdc, 0x2f, 0x29, 0xb1, 0x9a, 0x3d, 0x5d, 0x8c, 0x4c, 0xa8, 0x7c, 0x04, 0x2c,
	0x25, 0xfd, 0xf2, 0xd0, 0x18, 0x19, 0x9e, 0x7e, 0xd8, 0x2f, 0xd0, 0x3d, 0xb1, 0x15, 0x31, 0x8f,
	0x04, 0x41, 0x03, 0x68, 0xa8, 0x0e, 0x3f, 0x60, 0x2c, 0xb7, 0xaf, 0x2b, 0xe1, 0x9e, 0x31, 0x74,
	0x05, 0x1d, 0x99, 0xf0, 0x78, 0xfd, 0xe9, 0x2f, 0x39, 0x8d, 0xf6, 0xb3, 0x5a, 0x5a, 0xcd, 0x8c,
	0x5c, 0x6c, 0xbf, 0x81, 0xf9, 0x48, 0x19, 0x23, 0x78, 0xc6, 0x23, 0x21, 0x49, 0x72, 0x36, 0xf2,
	0x05, 0x40, 0xa8, 0xbf, 0x66, 0xb5, 0xb2, 0xaa, 0x35, 0x72, 0xc5, 0xc5, 0xf6, 0x2b, 0x74, 0x4f,
	0xfc, 0x73, 0xf6, 0x1e, 0xd4, 0x36, 0x12, 0x1f, 0x90, 0x57, 0x37, 0x12, 0x67, 0xdc, 0x37, 0x59,
	0x02, 0x8a, 0xfb, 0xc0, 0x57, 0xcf, 0xfc, 0xad, 0x0b, 0xb3, 0x9d, 0xfb, 0x0a, 0x5a, 0x0f, 0x24,
	0x90, 0xeb, 0xb3, 0xa9, 0x1d, 0xf8, 0x95, 0x85, 0xa7, 0x78, 0x9b, 0x13, 0xcb, 0xd1, 0xc9, 0x3a,
	0xdb, 0x64, 0x9d, 0xf9, 0x36, 0x59, 0x4f, 0xf5, 0xd9, 0x4f, 0xd0, 0xce, 0x07, 0xfd, 0x84, 0x7f,
	0x0d, 0x39, 0xa5, 0x8f, 0xb3, 0x0f, 0xfb, 0xd1, 0x6d, 0x2d, 0x2b, 0x1b, 0x17, 0x4f, 0xbe, 0x0c,
	0x68, 0xce, 0xf7, 0x97, 0x86, 0x66, 0xf0, 0x47, 0x10, 0x79, 0x94, 0x33, 0x1a, 0x38, 0xea, 0xf0,
	0x9c, 0xa2, 0xa3, 0xb2, 0xfe, 0x17, 0x17, 0x73, 0x3e, 0x6d, 0x77, 0xb4, 0xfa, 0x9d, 0x5d, 0x51,
	0xe0, 0x3b, 0xbb, 0xe2, 0xb4, 0xee, 0xa0, 0x2e, 0x88, 0x54, 0xec, 0xe8, 0x5f, 0xde, 0x79, 0xb8,
	0x79, 0xcb, 0x3c, 0x16, 0xf5, 0xb7, 0x45, 0x55, 0x2d, 0xf4, 0xf6, 0x3b, 0x00, 0x00, 0xff, 0xff,
	0x17, 0xb5, 0x1e, 0xa4, 0x54, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TransactionClient is the client API for Transaction service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TransactionClient interface {
	SetCollectedCoin(ctx context.Context, in *CollectedCoinRequest, opts ...grpc.CallOption) (*CollectedCoinResponse, error)
	SetKilledMonster(ctx context.Context, in *KilledMonsterRequest, opts ...grpc.CallOption) (*KilledMonsterResponse, error)
	SetDeath(ctx context.Context, in *DeathRequest, opts ...grpc.CallOption) (*DeathResponse, error)
}

type transactionClient struct {
	cc *grpc.ClientConn
}

func NewTransactionClient(cc *grpc.ClientConn) TransactionClient {
	return &transactionClient{cc}
}

func (c *transactionClient) SetCollectedCoin(ctx context.Context, in *CollectedCoinRequest, opts ...grpc.CallOption) (*CollectedCoinResponse, error) {
	out := new(CollectedCoinResponse)
	err := c.cc.Invoke(ctx, "/model.Transaction/setCollectedCoin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionClient) SetKilledMonster(ctx context.Context, in *KilledMonsterRequest, opts ...grpc.CallOption) (*KilledMonsterResponse, error) {
	out := new(KilledMonsterResponse)
	err := c.cc.Invoke(ctx, "/model.Transaction/setKilledMonster", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionClient) SetDeath(ctx context.Context, in *DeathRequest, opts ...grpc.CallOption) (*DeathResponse, error) {
	out := new(DeathResponse)
	err := c.cc.Invoke(ctx, "/model.Transaction/setDeath", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TransactionServer is the server API for Transaction service.
type TransactionServer interface {
	SetCollectedCoin(context.Context, *CollectedCoinRequest) (*CollectedCoinResponse, error)
	SetKilledMonster(context.Context, *KilledMonsterRequest) (*KilledMonsterResponse, error)
	SetDeath(context.Context, *DeathRequest) (*DeathResponse, error)
}

// UnimplementedTransactionServer can be embedded to have forward compatible implementations.
type UnimplementedTransactionServer struct {
}

func (*UnimplementedTransactionServer) SetCollectedCoin(ctx context.Context, req *CollectedCoinRequest) (*CollectedCoinResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetCollectedCoin not implemented")
}
func (*UnimplementedTransactionServer) SetKilledMonster(ctx context.Context, req *KilledMonsterRequest) (*KilledMonsterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetKilledMonster not implemented")
}
func (*UnimplementedTransactionServer) SetDeath(ctx context.Context, req *DeathRequest) (*DeathResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetDeath not implemented")
}

func RegisterTransactionServer(s *grpc.Server, srv TransactionServer) {
	s.RegisterService(&_Transaction_serviceDesc, srv)
}

func _Transaction_SetCollectedCoin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CollectedCoinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServer).SetCollectedCoin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/model.Transaction/SetCollectedCoin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServer).SetCollectedCoin(ctx, req.(*CollectedCoinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Transaction_SetKilledMonster_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KilledMonsterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServer).SetKilledMonster(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/model.Transaction/SetKilledMonster",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServer).SetKilledMonster(ctx, req.(*KilledMonsterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Transaction_SetDeath_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeathRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServer).SetDeath(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/model.Transaction/SetDeath",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServer).SetDeath(ctx, req.(*DeathRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Transaction_serviceDesc = grpc.ServiceDesc{
	ServiceName: "model.Transaction",
	HandlerType: (*TransactionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "setCollectedCoin",
			Handler:    _Transaction_SetCollectedCoin_Handler,
		},
		{
			MethodName: "setKilledMonster",
			Handler:    _Transaction_SetKilledMonster_Handler,
		},
		{
			MethodName: "setDeath",
			Handler:    _Transaction_SetDeath_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "transaction.proto",
}
