// Code generated by protoc-gen-go. DO NOT EDIT.
// source: trophy.proto

package model

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DefaultRequest struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DefaultRequest) Reset()         { *m = DefaultRequest{} }
func (m *DefaultRequest) String() string { return proto.CompactTextString(m) }
func (*DefaultRequest) ProtoMessage()    {}
func (*DefaultRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8e914ec0c2ee928, []int{0}
}

func (m *DefaultRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DefaultRequest.Unmarshal(m, b)
}
func (m *DefaultRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DefaultRequest.Marshal(b, m, deterministic)
}
func (m *DefaultRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DefaultRequest.Merge(m, src)
}
func (m *DefaultRequest) XXX_Size() int {
	return xxx_messageInfo_DefaultRequest.Size(m)
}
func (m *DefaultRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DefaultRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DefaultRequest proto.InternalMessageInfo

func (m *DefaultRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type TrophyCoinResponse struct {
	ValueAll             int64    `protobuf:"varint,1,opt,name=value_all,json=valueAll,proto3" json:"value_all,omitempty"`
	TrophyCoinId         int64    `protobuf:"varint,2,opt,name=trophy_coin_id,json=trophyCoinId,proto3" json:"trophy_coin_id,omitempty"`
	TrophyCoinStarting   int64    `protobuf:"varint,3,opt,name=trophy_coin_starting,json=trophyCoinStarting,proto3" json:"trophy_coin_starting,omitempty"`
	TrophyCoinName       string   `protobuf:"bytes,4,opt,name=trophy_coin_name,json=trophyCoinName,proto3" json:"trophy_coin_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TrophyCoinResponse) Reset()         { *m = TrophyCoinResponse{} }
func (m *TrophyCoinResponse) String() string { return proto.CompactTextString(m) }
func (*TrophyCoinResponse) ProtoMessage()    {}
func (*TrophyCoinResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8e914ec0c2ee928, []int{1}
}

func (m *TrophyCoinResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrophyCoinResponse.Unmarshal(m, b)
}
func (m *TrophyCoinResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrophyCoinResponse.Marshal(b, m, deterministic)
}
func (m *TrophyCoinResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrophyCoinResponse.Merge(m, src)
}
func (m *TrophyCoinResponse) XXX_Size() int {
	return xxx_messageInfo_TrophyCoinResponse.Size(m)
}
func (m *TrophyCoinResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TrophyCoinResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TrophyCoinResponse proto.InternalMessageInfo

func (m *TrophyCoinResponse) GetValueAll() int64 {
	if m != nil {
		return m.ValueAll
	}
	return 0
}

func (m *TrophyCoinResponse) GetTrophyCoinId() int64 {
	if m != nil {
		return m.TrophyCoinId
	}
	return 0
}

func (m *TrophyCoinResponse) GetTrophyCoinStarting() int64 {
	if m != nil {
		return m.TrophyCoinStarting
	}
	return 0
}

func (m *TrophyCoinResponse) GetTrophyCoinName() string {
	if m != nil {
		return m.TrophyCoinName
	}
	return ""
}

type TrophyDeathResponse struct {
	ValueAll             int64    `protobuf:"varint,1,opt,name=value_all,json=valueAll,proto3" json:"value_all,omitempty"`
	TrophyDeathId        int64    `protobuf:"varint,2,opt,name=trophy_death_id,json=trophyDeathId,proto3" json:"trophy_death_id,omitempty"`
	TrophyDeathStarting  int64    `protobuf:"varint,3,opt,name=trophy_death_starting,json=trophyDeathStarting,proto3" json:"trophy_death_starting,omitempty"`
	TrophyDeathName      string   `protobuf:"bytes,4,opt,name=trophy_death_name,json=trophyDeathName,proto3" json:"trophy_death_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TrophyDeathResponse) Reset()         { *m = TrophyDeathResponse{} }
func (m *TrophyDeathResponse) String() string { return proto.CompactTextString(m) }
func (*TrophyDeathResponse) ProtoMessage()    {}
func (*TrophyDeathResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8e914ec0c2ee928, []int{2}
}

func (m *TrophyDeathResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrophyDeathResponse.Unmarshal(m, b)
}
func (m *TrophyDeathResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrophyDeathResponse.Marshal(b, m, deterministic)
}
func (m *TrophyDeathResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrophyDeathResponse.Merge(m, src)
}
func (m *TrophyDeathResponse) XXX_Size() int {
	return xxx_messageInfo_TrophyDeathResponse.Size(m)
}
func (m *TrophyDeathResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TrophyDeathResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TrophyDeathResponse proto.InternalMessageInfo

func (m *TrophyDeathResponse) GetValueAll() int64 {
	if m != nil {
		return m.ValueAll
	}
	return 0
}

func (m *TrophyDeathResponse) GetTrophyDeathId() int64 {
	if m != nil {
		return m.TrophyDeathId
	}
	return 0
}

func (m *TrophyDeathResponse) GetTrophyDeathStarting() int64 {
	if m != nil {
		return m.TrophyDeathStarting
	}
	return 0
}

func (m *TrophyDeathResponse) GetTrophyDeathName() string {
	if m != nil {
		return m.TrophyDeathName
	}
	return ""
}

type TrophyMonsterResponse struct {
	KilledMonster        []*KilledMonster `protobuf:"bytes,1,rep,name=killed_monster,json=killedMonster,proto3" json:"killed_monster,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *TrophyMonsterResponse) Reset()         { *m = TrophyMonsterResponse{} }
func (m *TrophyMonsterResponse) String() string { return proto.CompactTextString(m) }
func (*TrophyMonsterResponse) ProtoMessage()    {}
func (*TrophyMonsterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8e914ec0c2ee928, []int{3}
}

func (m *TrophyMonsterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrophyMonsterResponse.Unmarshal(m, b)
}
func (m *TrophyMonsterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrophyMonsterResponse.Marshal(b, m, deterministic)
}
func (m *TrophyMonsterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrophyMonsterResponse.Merge(m, src)
}
func (m *TrophyMonsterResponse) XXX_Size() int {
	return xxx_messageInfo_TrophyMonsterResponse.Size(m)
}
func (m *TrophyMonsterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TrophyMonsterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TrophyMonsterResponse proto.InternalMessageInfo

func (m *TrophyMonsterResponse) GetKilledMonster() []*KilledMonster {
	if m != nil {
		return m.KilledMonster
	}
	return nil
}

type KilledMonster struct {
	ValueAll              int64    `protobuf:"varint,1,opt,name=value_all,json=valueAll,proto3" json:"value_all,omitempty"`
	TrophyId              int64    `protobuf:"varint,2,opt,name=trophy_id,json=trophyId,proto3" json:"trophy_id,omitempty"`
	TrophyMonsterId       int64    `protobuf:"varint,3,opt,name=trophy_monster_id,json=trophyMonsterId,proto3" json:"trophy_monster_id,omitempty"`
	TrophyMonsterStarting int64    `protobuf:"varint,4,opt,name=trophy_monster_starting,json=trophyMonsterStarting,proto3" json:"trophy_monster_starting,omitempty"`
	TrophyMonsterName     string   `protobuf:"bytes,5,opt,name=trophy_monster_name,json=trophyMonsterName,proto3" json:"trophy_monster_name,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *KilledMonster) Reset()         { *m = KilledMonster{} }
func (m *KilledMonster) String() string { return proto.CompactTextString(m) }
func (*KilledMonster) ProtoMessage()    {}
func (*KilledMonster) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8e914ec0c2ee928, []int{4}
}

func (m *KilledMonster) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KilledMonster.Unmarshal(m, b)
}
func (m *KilledMonster) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KilledMonster.Marshal(b, m, deterministic)
}
func (m *KilledMonster) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KilledMonster.Merge(m, src)
}
func (m *KilledMonster) XXX_Size() int {
	return xxx_messageInfo_KilledMonster.Size(m)
}
func (m *KilledMonster) XXX_DiscardUnknown() {
	xxx_messageInfo_KilledMonster.DiscardUnknown(m)
}

var xxx_messageInfo_KilledMonster proto.InternalMessageInfo

func (m *KilledMonster) GetValueAll() int64 {
	if m != nil {
		return m.ValueAll
	}
	return 0
}

func (m *KilledMonster) GetTrophyId() int64 {
	if m != nil {
		return m.TrophyId
	}
	return 0
}

func (m *KilledMonster) GetTrophyMonsterId() int64 {
	if m != nil {
		return m.TrophyMonsterId
	}
	return 0
}

func (m *KilledMonster) GetTrophyMonsterStarting() int64 {
	if m != nil {
		return m.TrophyMonsterStarting
	}
	return 0
}

func (m *KilledMonster) GetTrophyMonsterName() string {
	if m != nil {
		return m.TrophyMonsterName
	}
	return ""
}

func init() {
	proto.RegisterType((*DefaultRequest)(nil), "model.DefaultRequest")
	proto.RegisterType((*TrophyCoinResponse)(nil), "model.TrophyCoinResponse")
	proto.RegisterType((*TrophyDeathResponse)(nil), "model.TrophyDeathResponse")
	proto.RegisterType((*TrophyMonsterResponse)(nil), "model.TrophyMonsterResponse")
	proto.RegisterType((*KilledMonster)(nil), "model.KilledMonster")
}

func init() { proto.RegisterFile("trophy.proto", fileDescriptor_f8e914ec0c2ee928) }

var fileDescriptor_f8e914ec0c2ee928 = []byte{
	// 422 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0x41, 0xcf, 0xd2, 0x30,
	0x1c, 0xc6, 0x53, 0x79, 0x41, 0xf8, 0xeb, 0x06, 0x14, 0x16, 0x26, 0x78, 0x20, 0x8b, 0x31, 0xd3,
	0xc3, 0x62, 0x30, 0xf1, 0xe2, 0x89, 0x40, 0x62, 0x16, 0xa3, 0x87, 0xc9, 0x7d, 0x99, 0xb6, 0xc2,
	0x42, 0xb7, 0xe2, 0xd6, 0x99, 0xf8, 0xb9, 0xbc, 0xf9, 0x4d, 0x3c, 0xf8, 0x5d, 0xcc, 0xba, 0xb2,
	0xad, 0x8b, 0x98, 0xf7, 0xb8, 0xf6, 0x79, 0x9e, 0xfe, 0xfa, 0xf4, 0x3f, 0x78, 0x2c, 0x32, 0x7e,
	0x39, 0xfd, 0xf0, 0x2e, 0x19, 0x17, 0x1c, 0xf7, 0x13, 0x4e, 0x28, 0x73, 0x5e, 0x80, 0xb9, 0xa7,
	0x5f, 0xa3, 0x82, 0x89, 0x80, 0x7e, 0x2b, 0x68, 0x2e, 0xf0, 0x02, 0x1e, 0x16, 0x39, 0xcd, 0xc2,
	0x98, 0xd8, 0x68, 0x8d, 0xdc, 0x5e, 0x30, 0x28, 0x3f, 0x7d, 0xe2, 0xfc, 0x44, 0x80, 0x0f, 0x32,
	0x62, 0xc7, 0xe3, 0x34, 0xa0, 0xf9, 0x85, 0xa7, 0x39, 0xc5, 0x2b, 0x18, 0x7d, 0x8f, 0x58, 0x41,
	0xc3, 0x88, 0x31, 0xe5, 0x18, 0xca, 0x85, 0x2d, 0x63, 0xf8, 0x19, 0x98, 0xd5, 0xa9, 0xe1, 0x17,
	0x1e, 0xa7, 0x65, 0xe6, 0x03, 0xa9, 0x50, 0x2c, 0x65, 0x90, 0x4f, 0xf0, 0x2b, 0x98, 0xb7, 0x55,
	0xb9, 0x88, 0x32, 0x11, 0xa7, 0x47, 0xbb, 0x27, 0xb5, 0xb8, 0xd1, 0x7e, 0x52, 0x3b, 0xd8, 0x85,
	0x49, 0xdb, 0x91, 0x46, 0x09, 0xb5, 0xef, 0xd6, 0xc8, 0x1d, 0x05, 0x66, 0xa3, 0xfe, 0x18, 0x25,
	0xd4, 0xf9, 0x85, 0x60, 0x56, 0x51, 0xef, 0x69, 0x24, 0x4e, 0xf7, 0xc3, 0x7e, 0x0e, 0x63, 0x15,
	0x4f, 0x4a, 0x53, 0xc3, 0x6d, 0x88, 0x26, 0xca, 0x27, 0x78, 0x03, 0x96, 0xa6, 0xeb, 0x90, 0xcf,
	0x5a, 0xea, 0x1a, 0xfd, 0x25, 0x4c, 0x35, 0x4f, 0x8b, 0x7d, 0xdc, 0xd2, 0x4b, 0xf8, 0x03, 0x58,
	0x15, 0xfb, 0x07, 0x9e, 0xe6, 0x82, 0x66, 0x35, 0xfd, 0x5b, 0x30, 0xcf, 0x31, 0x63, 0x94, 0x84,
	0x49, 0xb5, 0x63, 0xa3, 0x75, 0xcf, 0x7d, 0xb4, 0x99, 0x7b, 0xf2, 0x59, 0xbd, 0xf7, 0x72, 0xf3,
	0xea, 0x32, 0xce, 0xed, 0x4f, 0xe7, 0x0f, 0x02, 0x43, 0x13, 0xfc, 0xbf, 0x8c, 0x15, 0x8c, 0x14,
	0x70, 0x5d, 0xc3, 0xb0, 0x5a, 0xf0, 0x49, 0xeb, 0x36, 0x0a, 0xa4, 0x14, 0x55, 0xb7, 0x57, 0xb7,
	0x51, 0x67, 0xf8, 0x04, 0xbf, 0x81, 0x45, 0x47, 0x5b, 0xf7, 0x75, 0x27, 0x1d, 0x96, 0xe6, 0xa8,
	0x1b, 0xf3, 0x60, 0xd6, 0xf1, 0xc9, 0xce, 0xfa, 0xb2, 0xb3, 0xa9, 0xe6, 0x29, 0x5b, 0xdb, 0xfc,
	0x46, 0x30, 0xa8, 0x6a, 0xc3, 0x5b, 0x30, 0x8e, 0x54, 0x34, 0x53, 0x8b, 0x2d, 0x55, 0x90, 0x3e,
	0xf4, 0xcb, 0x27, 0x6a, 0xf9, 0x1f, 0xf3, 0xbd, 0x03, 0xb3, 0x8e, 0x90, 0x2f, 0x73, 0x2b, 0x63,
	0xa9, 0x65, 0xe8, 0xd3, 0xf6, 0x0e, 0x26, 0x75, 0xc8, 0xb5, 0xf4, 0x1b, 0x31, 0x4f, 0xb5, 0x98,
	0xce, 0xc3, 0x7f, 0x1e, 0xc8, 0xbf, 0xf7, 0xf5, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x1a, 0x27,
	0xd3, 0x19, 0xcd, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TrophyClient is the client API for Trophy service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TrophyClient interface {
	GetTrophyCoin(ctx context.Context, in *DefaultRequest, opts ...grpc.CallOption) (*TrophyCoinResponse, error)
	GetTrophyDeath(ctx context.Context, in *DefaultRequest, opts ...grpc.CallOption) (*TrophyDeathResponse, error)
	GetTrophyMonster(ctx context.Context, in *DefaultRequest, opts ...grpc.CallOption) (*TrophyMonsterResponse, error)
}

type trophyClient struct {
	cc *grpc.ClientConn
}

func NewTrophyClient(cc *grpc.ClientConn) TrophyClient {
	return &trophyClient{cc}
}

func (c *trophyClient) GetTrophyCoin(ctx context.Context, in *DefaultRequest, opts ...grpc.CallOption) (*TrophyCoinResponse, error) {
	out := new(TrophyCoinResponse)
	err := c.cc.Invoke(ctx, "/model.Trophy/getTrophyCoin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trophyClient) GetTrophyDeath(ctx context.Context, in *DefaultRequest, opts ...grpc.CallOption) (*TrophyDeathResponse, error) {
	out := new(TrophyDeathResponse)
	err := c.cc.Invoke(ctx, "/model.Trophy/getTrophyDeath", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trophyClient) GetTrophyMonster(ctx context.Context, in *DefaultRequest, opts ...grpc.CallOption) (*TrophyMonsterResponse, error) {
	out := new(TrophyMonsterResponse)
	err := c.cc.Invoke(ctx, "/model.Trophy/getTrophyMonster", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TrophyServer is the server API for Trophy service.
type TrophyServer interface {
	GetTrophyCoin(context.Context, *DefaultRequest) (*TrophyCoinResponse, error)
	GetTrophyDeath(context.Context, *DefaultRequest) (*TrophyDeathResponse, error)
	GetTrophyMonster(context.Context, *DefaultRequest) (*TrophyMonsterResponse, error)
}

// UnimplementedTrophyServer can be embedded to have forward compatible implementations.
type UnimplementedTrophyServer struct {
}

func (*UnimplementedTrophyServer) GetTrophyCoin(ctx context.Context, req *DefaultRequest) (*TrophyCoinResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTrophyCoin not implemented")
}
func (*UnimplementedTrophyServer) GetTrophyDeath(ctx context.Context, req *DefaultRequest) (*TrophyDeathResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTrophyDeath not implemented")
}
func (*UnimplementedTrophyServer) GetTrophyMonster(ctx context.Context, req *DefaultRequest) (*TrophyMonsterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTrophyMonster not implemented")
}

func RegisterTrophyServer(s *grpc.Server, srv TrophyServer) {
	s.RegisterService(&_Trophy_serviceDesc, srv)
}

func _Trophy_GetTrophyCoin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DefaultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrophyServer).GetTrophyCoin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/model.Trophy/GetTrophyCoin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrophyServer).GetTrophyCoin(ctx, req.(*DefaultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Trophy_GetTrophyDeath_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DefaultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrophyServer).GetTrophyDeath(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/model.Trophy/GetTrophyDeath",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrophyServer).GetTrophyDeath(ctx, req.(*DefaultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Trophy_GetTrophyMonster_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DefaultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrophyServer).GetTrophyMonster(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/model.Trophy/GetTrophyMonster",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrophyServer).GetTrophyMonster(ctx, req.(*DefaultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Trophy_serviceDesc = grpc.ServiceDesc{
	ServiceName: "model.Trophy",
	HandlerType: (*TrophyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getTrophyCoin",
			Handler:    _Trophy_GetTrophyCoin_Handler,
		},
		{
			MethodName: "getTrophyDeath",
			Handler:    _Trophy_GetTrophyDeath_Handler,
		},
		{
			MethodName: "getTrophyMonster",
			Handler:    _Trophy_GetTrophyMonster_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "trophy.proto",
}
